### ISSUE TITLE
Constantly freezes after 5,100 files

### ISSUE THREAD

**Issue by Tamalero** [martok/ImageHash#7]
Hi!

I was a big fan of using Visipics, but its limitations have forced me to find an alternative. For example. Visipics is 32 bits and it freezes and crashes also above a certain threshold of images.
For example, it starts to bogdown after 4500 images, then freezes around the 5,100 mark consistently WHEN SELECTING MULTIPLE DIRECTORIES WITH MULTIPLE SUB LEVELS.
Selecting a single directory with a single set of subdirectories seems to work up to 14,000 images.

Infact, the moment I select another set of directories. It freezes.

ImageHash also seems to be 32 bits, correct?

Is there a proper way to compile a version to handle larger number of files?

My specs:

13900k, 64GB RAM, 4090 RTX (and plenty of storage)

**Comment by martok** [comment]
Hm, this is strange: I regularly use it on folders totalling something north of 40,000 files. In VisiPics that was an overnight thing, in ImageHash it takes about 10 minutes.

I even used to build 64bit versions of ImageHash, but since switching the memory manager those 40k files need just 70MB of RAM. That shouldn't be the issue.

The only thing that really could use a lot of memory is the parallel loader if you have many very high-res images and end up loading multiple of them at the same time. Shouldn't freeze anything, but could at least run into issues where the loader gives up after a bit. Try lowering the scanner threads to something like 8, does that help?

**Comment by taboo180** [comment]
Hey bud! Been loving your app since you tweaked it for me 😊

Interestingly I just did a run of 76,000 images and mine too froze at 21,000 (you know when it does coz all your computer fans stop going full blast 😂). I was going to make my own issue but saw this guy has the same/similar problem.

I tried your suggestion of dropping from 11 to 8 threads (Ryzen 5 7600) and that got me to 29,000. So I dropped further to 5 threads and it has completed on that run.

Not sure if that information helps or not but figured I'd help with my experience 😊. Thanks again for fulling the hole Visipics started.

**Comment by martok** [comment]
Ah, fascinating, that helps!

Fans turning on means it's not a deadlock as I suspected, but reducing cores still makes me think it is either a race condition (with a live-lock) or a decoder memory issue that leads to a loop.

Do you happen to know if you have any especially large (>60M px) images, and if so, which file formats (JPEG, PNG, ...)?

@taboo180 One more question, does it actually *stop* or does just the frontend hang? I can kinda reproduce that by oversubscribing my 8 threads CPU using 16 loader threads. It does finish as normal, but the UI (apart from the progress bars for some reason, those still work) becomes unresponsive until everything is finished.

**Comment by taboo180** [comment]
So what would happen for me:

- Add a folder with a handful of subfolders.
- Start the run and it would show there's ~76,000 total images and start progressing through them.
- Continue doing my usual activities, browsing the web/word processing etc. and I'd leave ImageHash running.
- After 5-10mins notice my fans have stopped so go to check on ImageHash. Clicking its icon on my task bar would refuse to focus on the window as though the program has completely crashed.
- Hovering on the icon on my taskbar will temporarily let me see the state of the window and it would show 20,996/76,000 images processed and the number does not change if you wait.

I then have no way of bringing the window into focus or interacting with it so all I can do is kill the exe from task manager, reopen ImageHash and start the run again, dropping the cores to it progresses further each time.

As for your question around image size. I just searched that folder and subfolders for all files of "kind:=picture" and sorted by size:
- The majority are small - 63,000 out of 71,000 are <3MB each.
- ~1,200 are >60MB all the way up to 100MB as the largest (all of them .gif)
- And there's about 1,400 between 20-60MB (the majority .gif).

Every single image over 27MB is a .gif and the overwhelming majority of the rest are .jpg/.jpeg

![image](https://github.com/user-attachments/assets/047fd45d-c132-467c-922c-126f35dd6a3a)


Thanks.

**Comment by martok** [comment]
Alright, so.
The only freeze I can reproduce is a frontend freeze if you're oversubscribed(*) and attempt to do anything interactive. Just letting it run in the background works, so the count you get to might just be the point where you check back and try to work with the still-scanning results. I've narrowed it down logically (looks like Win10 changed some message dispatch rules and my old knowledge is useless), but a proper fix will take a few more days.
My first attempt worked, but came at a 10% performance penalty. So I went and optimized the loader by about 25% and now it is fast enough that the issue is back :sweat_smile:

*) My antique 4C/8T i7-6700 starts having problems at 12Threads, while your 6C/12T R5 7600 breaks immediately over 6 Threads, guessing from what you wrote. Apparently AMD SMT is *much* worse than Intel HT when you're actually making all threads do stuff.

Technical detail: there is something going on where you can completely swamp the message queue to the point that it never idles, which means the low-prio paint and input messages are not generated. Looks frozen then, including Windows' "(not responding)" frame decoration.

**Comment by martok** [comment]
I've just pushed the 1.2 release, let me know how it goes!
The original issue never happend for me, but with the changes made the one with too many threads is gone. I can now run 16 loader threads on an 4C/8T CPU without frontend issues.

**Comment by Tamalero** [comment]
Appreciate Martok!

**Comment by Tamalero** [comment]
Just FYI, I tried, and its still freezing after 50k images, I reduced the number of threads and it went to 97k.

The GUI seems to freeze.
Is there a way to give proper logs?



*edit 2*

Reduced the number of threads 8 to, and assigned them to P cores...
Somehow also freezes at around 93k of 495k
Aka cpu usage goes down to 0.. then "not responding".

Going to test again with only 4 threads.

*edit 3*

Went past 90k but it now threw a random error but continued to work ("Cannot load handles" ) then froze at 100k.

*edit*4
I tried a few methods, including forcing the program to only use main P cores, only E cores.. I'm going to try using only main threads.

*edit 5*

I have tried using P cores with no SMT, P cores, only Ecores.. stsill crashes around 100k out of 493k images.

On smaller collection of images, it works fine.
Could be that my nested directory structure is way too long?

Because if I add directory by directory.. It seems to work better and advances more.

*edit 6*

Still crashes after 99k using ECORES only and adding directories one by one.

Here is the errors that start appearing:
https://i.imgur.com/Q8UUaTm.png

The interesting part is, if you click on OK fast enough, the program will keep going with no issues. But if you take more than 5 seconds. the program will freeze like before

**Comment by martok** [comment]
495k? Jeepers. This is far beyond design goals and might actually get closer to the address space limit.

56k worked just fine here earlier today with 16 threads, although from an spinning disk so it was mostly IO bound. About 220MB RAM, so 500k should be about 2GB. IH is compiled with LAA, so it should be safe to 3GB.

I'll have to grep for that error message, but there's only like 3 places where something even uses Windows handles in the loop, specifically because Windows only lets you hold a few thousand.

I don't think that's really related, but how long are your file names on the "deeper" directories? I don't believe I set the flag for path names > 256 characters.

Edit: can you check in Task Manager using the Handles, User Objects and GDI Objects columns if any of them is actually large when the error messages pop up? In my tests they basically don't increase at all during a run.
~It's also weird that you see this message at all, it is only raised when creating images in memory, but the only thing creating bitmaps is the loader - which suppresses all errors and carries on.~ Scratch that, loading the large images on hover obviously also creates one. Hm.

**Comment by martok** [comment]
Soo, some more optimizations in 1.3.

> it is only raised when creating images in memory, but the only thing creating bitmaps is the loader

There is some absolutely bonkers logic in the LCL that creates a test bitmap to find font height every time a list row(!) is redrawn which is worked around now.

I've synthesized a larger test data set *on my SSD this time* by liberal use of directory hardlinks. Since there's a limited number of real files behind that, every single one ends up in a cluster, but that's the best I can do.

This uncovered a few loader issues where retries would not have worked, but it should still have failed-safe. It's fixed now, probably. Refreshing the list is also much more efficient now.

There is one UX issue: when an image fails to load on the first attempt, the classifier stops there until the image is loaded (or finally not loaded) on the single-threaded second attempt. Worst case, the classifier runs after the loaders, as if you clicked the "rerun" button. Changing that would require changes to the work dispatch logic which I honestly can't be bothered to make.

From a previous run, 93k files: no major issues.

![image](https://github.com/user-attachments/assets/6351b819-35da-4031-ad58-2bd928285a0e)
```
- had EOutOfMemory, rerunning errors single-threaded
time:  2189094ms
clusters: 52121 / 93389
clusters>1: 40295
```

An even larger test with 250k linked files got me the first actual crash at around 150k files loaded. This time in something where I know what's going on, but since it takes 20 minutes to get there, that'll continue another day.

**Comment by Tamalero** [comment]
> 495k? Jeepers. This is far beyond design goals and might actually get closer to the address space limit.
> 
> 56k worked just fine here earlier today with 16 threads, although from an spinning disk so it was mostly IO bound. About 220MB RAM, so 500k should be about 2GB. IH is compiled with LAA, so it should be safe to 3GB.
> 
> I'll have to grep for that error message, but there's only like 3 places where something even uses Windows handles in the loop, specifically because Windows only lets you hold a few thousand.
> 
> I don't think that's really related, but how long are your file names on the "deeper" directories? I don't believe I set the flag for path names > 256 characters.
> 
> Edit: can you check in Task Manager using the Handles, User Objects and GDI Objects columns if any of them is actually large when the error messages pop up? In my tests they basically don't increase at all during a run. ~It's also weird that you see this message at all, it is only raised when creating images in memory, but the only thing creating bitmaps is the loader - which suppresses all errors and carries on.~ Scratch that, loading the large images on hover obviously also creates one. Hm.

My Directory structure is like this:

DRIVE:\XXXXXX\XXXXX\XXXX\By-Date\2024\2024-07
I have my collection ordered by year then by month.

with some files that can be a bit long like [2024-07-01 13ː05ː55 UTC] 1807762561481478152_1.jpg


*edit*
Newer version crashes sooner than the prior one. Is 100% stable by selecting directory per directory instead of selecting the parent directory.


SUGGESTION: Can you make the visibility of the images permanent instead of just appearing when you do ON HOVER?
It's like ON HOVER it loads a new image and keeps it on the viewer.
SUGGESTION 2: When adding a directory one at a time. It automatically "advances" on the list. Because right, if you open a directory.. then open a directory again, it will just switch the directory instead of adding another one to the list.

**Comment by martok** [comment]
> My Directory structure is like this:
> DRIVE:\XXXXXX\XXXXX\XXXX\By-Date\2024\2024-07 I have my collection ordered by year then by month.
> with some files that can be a bit long like [2024-07-01 13ː05ː55 UTC] 1807762561481478152_1.jpg

How long are the segments you X'ed out above? It doesn't matter how deep the hierarchy is, just the precise number of characters in what you enter into the scan list and in what you guess is the longest total file name. I.e. if you'd enter "C:\Users\Me\Pictures\Photos\\" and somewhere that finds "C:\Users\Me\Pictures\Photos\Vacation\2024\IMG00001.JPG" those would be 28 and 84.

> Newer version crashes sooner than the prior one. Is 100% stable by selecting directory per directory instead of selecting the parent directory.

Fascinating. There is no actual difference in image handling code if the subdirs are found automatically or entered manually... except maybe the order could be different. The scanner itself always sorts alphabetically.

Anyway, with the even larger test set I do in fact see a crash at 131k files loaded. This time it's something in Windows going really wrong, at that point it fails to allocate even a single page (4kB) of memory even if the entire process only uses 800MB. This is page table fragmentation gone *very* wrong.

> SUGGESTION: Can you make the visibility of the images permanent instead of just appearing when you do ON HOVER? It's like ON HOVER it loads a new image and keeps it on the viewer.

Isn't that super confusing? I don't like it. Anyway, #9.

> SUGGESTION 2: When adding a directory one at a time. It automatically "advances" on the list. Because right, if you open a directory.. then open a directory again, it will just switch the directory instead of adding another one to the list.

Yeah, the dirlist ist totally cursed. I've been working on building something better for this since before the first public version, but it's not as easy to get everything right that I want/need. I've created #8 just so that it is visible.

**Comment by Tamalero** [comment]
> > My Directory structure is like this:
> > DRIVE:\XXXXXX\XXXXX\XXXX\By-Date\2024\2024-07 I have my collection ordered by year then by month.
> > with some files that can be a bit long like [2024-07-01 13ː05ː55 UTC] 1807762561481478152_1.jpg
 
Each X's is equivalent to a single character.

> How long are the segments you X'ed out above? It doesn't matter how deep the hierarchy is, just the precise number of characters in what you enter into the scan list and in what you guess is the longest total file name. I.e. if you'd enter "C:\Users\Me\Pictures\Photos\" and somewhere that finds "C:\Users\Me\Pictures\Photos\Vacation\2024\IMG00001.JPG" those would be 28 and 84.
> 
> > Newer version crashes sooner than the prior one. Is 100% stable by selecting directory per directory instead of selecting the parent directory.
> 
> Fascinating. There is no actual difference in image handling code if the subdirs are found automatically or entered manually... except maybe the order could be different. The scanner itself always sorts alphabetically.

Could be perhaps a corrupted image causing the issue? I don't know on my side. It's hard to tell when you have a collection of images that big XD


> Anyway, with the even larger test set I do in fact see a crash at 131k files loaded. This time it's something in Windows going really wrong, at that point it fails to allocate even a single page (4kB) of memory even if the entire process only uses 800MB. This is page table fragmentation gone _very_ wrong.
> 
> > SUGGESTION: Can you make the visibility of the images permanent instead of just appearing when you do ON HOVER? It's like ON HOVER it loads a new image and keeps it on the viewer.
> 
> Isn't that super confusing? I don't like it. Anyway, #9.
> 
> > SUGGESTION 2: When adding a directory one at a time. It automatically "advances" on the list. Because right, if you open a directory.. then open a directory again, it will just switch the directory instead of adding another one to the list.
> 
> Yeah, the dirlist ist totally cursed. I've been working on building something better for this since before the first public version, but it's not as easy to get everything right that I want/need. I've created #8 just so that it is visible.

Sorry if I am being pushy. Wasnt my intention to shove this many things on your table XD

**Comment by martok** [comment]
> > > My Directory structure is like this:
> > > DRIVE:\XXXXXX\XXXXX\XXXX\By-Date\2024\2024-07 I have my collection ordered by year then by month.
> > > with some files that can be a bit long like [2024-07-01 13ː05ː55 UTC] 1807762561481478152_1.jpg
> 
> Each X's is equivalent to a single character.

Ah, I see.
This actually makes it even weirder, because from what I've learned yesterday, adding the parent folder should have reduced the errors. Longer paths relative to the base would be slightly more efficient, not less... those length are also not close to one of the "split points" in the allocator.

> Could be perhaps a corrupted image causing the issue? I don't know on my side. It's hard to tell when you have a collection of images that big XD

Maybe, I have a few PNGs that expand to >1GB during decompression, but those should just be ignored in the end.

> Sorry if I am being pushy. Wasnt my intention to shove this many things on your table XD

Haha no worries, I'll take it into account when I get back to working on the UI side.

(I have also randomly discovered that my compiler didn't generate the POPCNT instruction from the PopCnt intrinsic, that's fixed now and makes the classifier *a lot* faster, and since its runtime is quadratic, that gets more significant with larger data sets. Significant as in "on a 2 hour job, save one hour".)

---

> > Anyway, with the even larger test set I do in fact see a crash at 131k files loaded. This time it's something in Windows going really wrong, at that point it fails to allocate even a single page (4kB) of memory even if the entire process only uses 800MB. This is page table fragmentation gone _very_ wrong.

The rest of this post is brought to you by [VMMap](https://learn.microsoft.com/en-us/sysinternals/downloads/vmmap) and a few critical bits of information not in the MSDN docs. Writing it here so I can maybe some day remember it.

Fundamentally, VirtualAlloc (which backs the memory manager) can only give contiguous chunks of memory. So it doesn't matter if there are 3GB free, if they're all in 5MB chunks with already allocated stuff between, you simply can't request 100MB.

How might this happen?

For one thing, even large-adress-aware 32bit applications *usually* don't get the high 2GB mapped. Windows doesn't map a file or image (as in, DLL or EXE) or VirtualAllocs anything there unless it really has to. This means the low 0x7fff000 bytes get a lot more traffic. The "unless it has to" bit also means there's usually around 2GB contiguous memory there if required, so that's not too bad overall.

You also can't really VirtualAlloc anything smaller than 64kB (16 pages). I don't think this is documented anywhere as such, at least I couldn't find it. If you try, you just get a small chunk at the start of a 64k "segment". Notice how all starting addresses in yellow end with 4 zeroes, aka 16 bit, aka 64kB.
![image](https://github.com/user-attachments/assets/5a021e23-cf28-4f83-abf6-5a6f2f0bed78)

So, what happens if you write an "efficient" memory manager that allocates stuff in slices of around 2 Pages? Basically 15/16th of the address space ends up being unusable. Which is kinda bad.

Another thing that plays into this is [ASLR](https://en.wikipedia.org/wiki/Address_space_layout_randomization). Images can be mapped anywhere, and with any amount of more-or-less-usable amount of memory in between. This actually makes testing a bit harder, because each process start is slightly different in where it breaks.

What I have now done in ConcurrentMM is extend the SmallAlloc slices up to 64kB (i.e, this fits (with overhead) 9 default-size thumbnails instead of just one per 64kB).
With a few more fixes on OOM handling (and an emergency compaction, almost like a GC), my 215k files test case now doesn't die anymore, not even on the 75Mpx photos that are the reason the retry mechanic is thre in the first place.

I still don't think it'll work on 500k files, but it'll probably not-work less.

**Comment by Tamalero** [comment]
Good news, the latest version no longer crashes or freezes. It throws a few errors and there are some detection errors in the images (aka completely different images get grouped together) but the can passes and delivers very good results in detection that my other tools did not!

**Comment by martok** [comment]
Yay :tada:
